// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDck_DPUAw4MHimwdq6-j79sgW82Il_d68',
    appId: '1:186827998299:web:4eba0d2976551391ba2b7e',
    messagingSenderId: '186827998299',
    projectId: 'maya-firebase',
    authDomain: 'maya-firebase.firebaseapp.com',
    storageBucket: 'maya-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAksSlbGZYsu6mqkLTI5_Kz52FNEmcQWOc',
    appId: '1:186827998299:android:0d44e370374559f8ba2b7e',
    messagingSenderId: '186827998299',
    projectId: 'maya-firebase',
    storageBucket: 'maya-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5SGBWE3wZa_x22-fks7ExPKhVONONZX4',
    appId: '1:186827998299:ios:1af265ffbfdc6f48ba2b7e',
    messagingSenderId: '186827998299',
    projectId: 'maya-firebase',
    storageBucket: 'maya-firebase.appspot.com',
    iosBundleId: 'com.example.stateChangeDemo',
  );
}
